version: "3.8"

services:
  localtunnel-server:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - SERVICE_FQDN_TUNNEL
      - NODE_ENV=production
      - DOMAIN=$DOMAIN
      - PORT=$PORT
    restart: unless-stopped
