version: "3.8"

services:
  localtunnel-server:
    build: .
    ports:
      - "3000:3000"
      - "10000-20000:10000-20000" # Range for tunnel connections
    environment:
      - NODE_ENV=production
      - DOMAIN=$DOMAIN
    restart: unless-stopped
