version: "3.8"

services:
  localtunnel-server:
    build: .
    ports:
      - "{PORT}:3000"
      - "10000-20000:10000-20000" # Range for tunnel connections
    environment:
      - SERVICE_FQDN_TUNNEL
      - NODE_ENV=production
      - DOMAIN=$DOMAIN
      - PORT=$PORT
    restart: unless-stopped
