version: "3.8"

services:
  localtunnel-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOMAIN=${DOMAIN:backend.impressment.in}
    restart: unless-stopped
